### ISSUE TITLE
Improve memory efficiency

### ISSUE THREAD

**Issue by oertl** [HdrHistogram/HdrHistogram#54] opened 2015-03-18 21:30 UTC
Ideally, to ensure a given maximum relative error r the bucket boundaries must not differ by more than a factor of (1+r). If we want to cover a range [a,b], we need at least (log(b)-log(a))/log(1+r) bins.

The allocated array sizes of HDR histogram are often much larger than this theoretical limit. For example, `((Histogram)(new DoubleHistogram(130, 4).integerValuesHistogram)).counts.length` gives 163840 while the theoretically needed number of buckets is log(130)/log(1.0001) or approximately 48678 which is more than a factor 3 less.

Of course, using the optimal number of buckets, each with equal width on the logarithmic scale is not feasible, because the index function which maps a given value to the corresponding bucket would require costly evaluations of the logarithm. The key idea of the HDR histogram approach is to use slightly smaller buckets in such a way that the corresponding index function is less expensive. By nature, this optimization is at the expense of memory utilization. There are multiple effects which increase the memory costs of the HDR histogram approach:
* As far as I understand the HDR approach is only able to limit the relative error to values that are a power of 1/2. That means if a maximum relative error of 0.01 needs to be guaranteed, the HDR approch must limit the relative error to (1/2)^7 = 0.0078, because (1/2)^6 = 0.0156 is too large.
* Sequences of buckets of equal width (on the linear scale) range from some value to the double of that value. To cover the same range with buckets of equal width on the logarithmic scale approximately 30% less buckets would be required.
* I did not analyze the code in detail. However, I guess there are some other issues that further increase the memory costs, e.g. memory alignment, array resizing, auto-scaling?

Since I really liked the HDR key idea to use smaller bucket sizes to reduce indexing costs, I tried to find another index function that is more optimal regarding memory, but still cheap to evaluate. [Here](https://gist.github.com/oertl/60d52c9d308fecb5dc9d) is what I have got so far. The bucket sizes are only slightly reduced which means that not more than approx. 8% additional buckets (compared to the optimal number) are required to cover the given range while keeping the relative error below the specified maximum. First tests gave me an average recording time of about 6ns per value. Maybe the proposed approach can tackle both memory and CPU costs.

**Comment by giltene** [comment] 2015-03-19 07:59
I'm not sure I follow the math in your indexing function...

AFAICT, the index ends up being linear to ( (4*mantissa) - (mantissa^2) + (3*exponent)), where exponent is a power of two (not 10). The basic problem I see with this is that while values in the same order of magnitude can map to different indexes, values from different magnitudes can/will end up mapping to the same index. E.g. some value in the range 1024...2047 will end up with the same index as some other value in the range 8192...16383. If I read the math right, this mapping would cause data loss (an inability to reproduce the value distribution).

As you note, HdrHistogram is certainly not an optimal footprint data structure, and there are certainly somewhat-more compact structures that can be built, but those data structures likely require a much more expensive index computation function. I look at it in reverse: HdrHistogram provides a close approximation of optimal footprint, to within a scalar factor that is certainly smaller than 2 (and is probably around 1.3 using hand waving approximation rather than real math).

Internally, HdrHistogram provides "only ~twice as much" accuracy as required at one end of the spectrum of each exponential bucket (e.g. for 3 decimal points if accuracy, being able to distinguish between 2047 and 2046 when a separation of 2.046 is allowed) and more closely matches the required accuracy at the other end of the spectrum (e.g. being able to distinguish 1024 from 1025 for the same accuracy requirement). So the "waste" compared to optimal storage (for the required accuracy) obviously cannot be more than 2x, and can be as low as ~1.3x.

You can look at the "waste" in two parts: one "waste" part has to do with the linear-sub-bucket inside logarithmic bicker arrangement. That's the one that leads to 2x at one end and 1x at the other end of each bucket. This one would happen even if we kept to powers of 10 I stead if powers of 2. (e.g. Distinguishing 1999 vs 2000 instead of ~1998 vs 2000). The other "waste" part comes from using powers of two for number-of-linear-sub-bucket I stead if the power of 10 that the accuracy requirement is e pressed in. This bucket count mismatch varies by accuracy requirement (e.g. 100 vs. 128, or 1000 vs 1024, or 10000 vs 16384), but is always capped at 2x, and practically capped at 1.64x if accuracy is limited to 6 decimal points. But it's not all waste, as when more sub buckets than needed are used, they do reduce the number of logarithmic buckets needed, and thus still contribute to reducing the total number of sub buckets required to cover the range.

**Comment by oertl** [comment] 2015-03-19 20:08
Yes, the index follows ( (4mantissa) - (mantissa^2) + (3exponent)). The mantissa is always in the range [0, 1). Between powers of 2 the mantissa increases from 0 to 1. Hence, the mantissa term in the index function goes from 0 to 3. If the value reaches the next power of 2, its mantissa is reset to 0 and the exponent is incremented by 1. Therefore, the index function is monotonic increasing and cannot return the same index for different magnitudes.

The index function I have proposed is the result of following considerations: The optimal index function is ln(x/a)/ln(1+r) where a is the minimum value and r the maximum relative error. Any function that is monotonic increasing and for which the gradient is larger than the gradient of the optimal index function for all values x guarantees the specified relative error. Since the logarithm is inexpensive to compute for all powers of 2, the idea was to use a polynomial with a gradient as small as possible in between. The proposed index function uses a quadratic polynomial and it can be shown that this function is approximately (exactly at powers of 2) by a factor of 3/(4*ln(2))=1.082 larger than the optimal index function. This explains why it only requires about 8% more memory than the optimal solution. Using a linear polynomial instead results in an index function that requires only a single floating point multiplication but increases the value of the index function and the memory costs by a factor of 1/ln(2)=1.443.

Concerning the memory footprint of the HDR approach: Why does `new DoubleHistogram(130, 4)` allocate an array of size 163840, if the optimal bucket count would be 48678. This is much more than the factor 2 you mentioned.

**Comment by oertl** [comment] 2015-03-21 20:56
I did some more testing (see https://github.com/oertl/HdrHistogram/blob/memory_efficiency/src/test/java/org/HdrHistogram/PerformanceTest.java). I compared the average recording times for DoubleHistogram, Histogram and a raw implementation using the proposed indexing function (see https://github.com/oertl/HdrHistogram/blob/memory_efficiency/src/main/java/org/HdrHistogram/MemoryEfficientHistogram.java). This is the ouput I got for the performance test on a machine with an Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz and running java version 1.8.0_40.

`Avg recording time DoubleHistogram = 10.7774ns.`
`Size of count array of DoubleHistogram = 32768`
`Avg recording time MemoryEfficientHistogram (for double data) = 4.6972ns.`
`Size of count array of MemoryEfficientHistogram = 22437`
`Avg recording time Histogram = 6.8845ns.`
`Size of count array of Histogram = 22528`
`Avg recording time MemoryEfficientHistogram (for long data) = 5.055ns.`
`Size of count array of MemoryEfficientHistogram = 22437`

In case of double value recording the new approach seems to be faster by more than a factor 2 compared to DoubleHistogram and uses (as expected) significant less memory.

I also compared the new approach against Histogram in case of long data. Even in this case, the new approach is slightly faster, although it is not optimized for integral data types yet. Currently, a long value first needs a casting to double and then a transformation back to a long representation. I suppose it would be more efficient to determine the exponent and mantissa directly from the long representation using the number of leading zeros.

Interestingly, the Histogram's count array size is not larger than that of the MemoryEfficientHistogram in this test case. This is due to the fact, that Histogram saves a lot of buckets because it allows larger bucket widths for small values as long as the widths do not exceed the lowest discernible value. By contrast, the new approach always guarantees the predefined relative error. However, I can imagine that the new approach could also be modified to use a lower bound on bucket widths to get memory savings comparable to those obtained for double value recording.

**Comment by giltene** [comment] 2015-03-27 13:27
I think I follow the math now, and see the monotonic nature of the polynomial you chose. So correctness probably works.

Regarding space comparisons: my comments above are about the integer value forms size, which according to your numbers fall close to your polynomial based implementation (to with ~1%). Running some simple comparisons with the optimal math you suggest above also show the current integer implementation to be fairly efficient, especially when looking at a wide dynamic range (e.g. 10 orders of magnitude). E.g. when comparing the storage of Histogram for a dynamic range of 130000000000L against the optimal computation above for 5, 4, and 3 decimal places of precision, the "waste" in Histogram compared to optimal is 7.6%, 54%, and 12% respectively. That waste is probably driven more by the power of 2 rounding of the precision (e.g. 16384 entry half-buckets rather than 10000 in the case of 4 decimal points). My guess is that your polynomial based space requirements would be ~45% better than Histogram in the 4 decimal points precision case, but very similar in the 3 and 5 decimal places cases).

In the DoubleHistogram case, the current DoubleHistogram uses an integer values histogram as an underlying store. There are multiple inefficiencies in this overlay. The first is a "waste" of the entire bottom-most half-bucket (can't use it for floating point values due to lack of precision there). In addition, there is a an additional half-bucket added to the range to support auto-ranging. Both of these "wastes" get more pronounced as a % of the total with lower dynamic ranges as well as with higher precisions, but they don't account for the majority wasted space in DoubleHistogram. E.g. we show a ~100% waste (92% above the integer waste) compared to optimal at (130000000000L, 5) (5111808 actual slots vs an optimal 2559092), where the wasted half buckets would only account for an extra ~10%. I'd need to think more about where that waste comes from (e.g. the extensions of the magnitude range by the half-bucket count multiple accounts for some of it, but not all).

So it seems while there is not much to be gained for the integer storage in efficiency, the double histogram storage space could certainly be improved.

Regarding speed comparisons: I try to avoid drawing any early speed conclusions from simple loop numbers on very different logic and functionality. E.g. both the integer and double histogram implementations include logic for min, max, and total count tracking that is not being performed in your current MemoryEfficientHistogram.add() logic. They also deal with out-of-bounds values differently (exception handing vs. explicit checks). If you want to compare the performance numbers more closely, I'd match the current logic for min, max, total count, and out-of-range handling first. In addition, make sure you warm up the code first. E.g. by running each bench method twice and only considering the second result (or by building JMH based tests if you really want to get serious about it ;-) ). I do think that extracting the power of two of an integer value from an equivalent floating point exponent representation rather than from a find-first-one thing is "cool". It would certainly faster for an incoming floating point value, and it would be interesting to find out if it can actually be faster even for integer values on some processors.

**Comment by giltene** [comment] 2015-03-27 14:03
You mat also want to compare the speed of recording a constant value rather than random smear. This will eliminate potential differences in memory access patterns and let you see the differences in the speed of the logic itself. In reality, cache misses will tend to dominate cold recordings, but another reality is that in many cases (e.g. latency measurement) values tend to be strongly multi-modal (bunched around certain mode values), so cache locality is very effective for hot recording paths, especially in lower precision cases (2 or 3 decimal points).

**Comment by oertl** [comment] 2015-03-30 20:19
I made some improvements (see
https://github.com/oertl/HdrHistogram/tree/memory_efficiency_2) and added logic for min, max, and total count to allow a more fair comparison. Furthermore, I introduced a lower bound for the bin size, which is comparable to the lowest discernible value. I still get similar numbers for the test case, but now also integer recording requires significant less memory:
`Avg recording time MemoryEfficientHistogram (for long data) = 8.1901ns.`
`Size of count array of MemoryEfficientHistogram = 15958`
`Avg recording time MemoryEfficientHistogram (for double data) = 6.2019ns.`
`Size of count array of MemoryEfficientHistogram = 22437`
`Avg recording time DoubleHistogram = 10.7352ns.`
`Size of count array of DoubleHistogram = 32768`
`Avg recording time Histogram = 6.2275ns.`
`Size of count array of Histogram = 22528`

Regarding speed: The execution time for each test is more than 60s, which should be enough to reduce the effect of cold code. Furthermore, I do not think that cache misses of the recording array are a big issue, since all recording arrays are smaller than 256kB. If memory bandwidth was an issue, the test results would probably not show much difference, because all tests are fed with data from a huge array (>500MB) which cannot be cached. The test data values are all within the valid range. Hence, the way of out-of-range handling should have no influence either. I know, much more testing on different platforms and better performance tests would be necessary to draw a general conclusion about the performance of both approaches. However, I think the numbers are good enough to assume that the recording times of the new approach are at least comparable to those of HDR histogram. And together with its near optimal space requirements for any precision I think it is a promising alternative.

**Comment by alavrik** [comment] 2015-04-07 19:30
@oertl, this is neat idea! I don't think you mentioned it, but the inverse of the index function has a straightforward analytic solution too. The whole thing won't be useful without it.

If you have a fixed floating point range in mind, this is a simple and elegant solution. Working with dynamic ranges can be more challenging though.

Here are some plots (clickable) for those who are curious what the polynomial function looks like.

The polynomial approximating the logarithm:
[![image](https://cloud.githubusercontent.com/assets/241658/7031363/c6bf9efc-dd1f-11e4-8831-329afa78426a.png)](https://www.wolframalpha.com/input/?i=plot+1%2F4*%284*x%2F%282%5Efloor%28log%28x%29%2Flog%282%29%29%29+-+%28x%2F%282%5Efloor%28log%28x%29%2Flog%282%29%29%29%29%5E2+%2B+3*floor%28log%28x%29%2Flog%282%29%29%29+and+log%28x%29+for+x+%3D+1+to+1e6)

Difference between the two:
[![image](https://cloud.githubusercontent.com/assets/241658/7031410/0ac1044c-dd20-11e4-9b48-7491c8d288c3.png)](https://www.wolframalpha.com/input/?i=plot+%281%2F4*%284*x%2F%282%5Efloor%28log%28x%29%2Flog%282%29%29%29+-+%28x%2F%282%5Efloor%28log%28x%29%2Flog%282%29%29%29%29%5E2+%2B+3*floor%28log%28x%29%2Flog%282%29%29%29%2Flog%28x%29%29+for+x+%3D+1+to+1e53)

**Comment by oertl** [comment] 2015-04-07 20:23
@alavrik You have plotted the wrong function. It should be continuous and look like [here](http://www.wolframalpha.com/input/?i=plot+1%2f4*%28%285-x%2f%282^floor%28log%28x%29%2flog%282%29%29%29%29*%28x%2f%282^floor%28log%28x%29%2flog%282%29%29%29-1%29+%2b+3*floor%28log%28x%29%2flog%282%29%29%29+and+log%28x%29+for+x+%3d+1+to+1e6).

I did not worry about the inverse, because the most critical operation is recording. Finding the lower and upper bound of some bin with given index is not that critical in my opinion. However, I am sure it can be done more efficiently than bisection which has logarithmic costs. Are you sure that there exists an analytical solution for the inverse?

It is easy to use this indexing function in combination with dynamic ranges. You just have to keep track of an offset, which describes the index that is mapped to the first element of the counting array. Once the value range needs to be shifted, the elements within the counting array need to be shifted and the offset must be increased or decreased accordingly.

**Comment by alavrik** [comment] 2015-04-07 21:23
Ah that function makes more sense. I was looking at the function that was discussed in the comments above: `( (4mantissa) - (mantissa^2) + (3exponent))` and didn't check if it was equivalent to the function in the code.

What I meant by analytical solution is not a precise formula, but rather a simple way to calculate the inverse. I think it can be done in two steps. The value of the exponent can be obtained from the narrow integer range `[ceil(4/3 * index/factor), floor(4/3 * index/factor + 5/3)]` that corresponds to mantissa varying across [0, 1] range. After that, the value for the mantissa can be calculated by solving a quadratic equation. Correct me if I am wrong here.

**Comment by oertl** [comment] 2015-04-08 04:47
You are right, the inverse can be calculated that way in constant time. Good to know.

**Comment by oertl** [comment] 2015-04-10 19:15
If the index of a value x is calculated as
`index = floor((4m-m^2+3e)/(4*ln(1+r)))` where `x=(1+m)*2^e`with mantissa m in `[0,1)` and r is the relative error, the exponent and the mantissa of the lower bound of the corresponding histogram bin can be directly computed using:
`exponent = floor(4*ln(1+r)*index/3)`
`mantissa = 2-sqrt(4-3*((4*ln(1+r)*index/3)%1))`
`lower_bound = (1+mantissa)*2^exponent`
Replacing `index`by `index+1`gives the upper bound  of a bin.

**Comment by giltene** [comment] 2016-09-30 17:18
While the proposed encoding will probably improve memory efficiency to some degree (per the discussion above), and the means of calculating indexes by directly extracting mantissa and exponent parts of a double are cool, I've chosen to keep the current encoding since it has become commonly used across multiple language implementations and in the now common histogram encoding and log formats.

Closing the issue.

**Closed by giltene** 2016-09-30 17:18 UTC
