### ISSUE TITLE
linearBucketValues ArrayIndexOutOfBoundsException 

### ISSUE THREAD

**Issue by slandelle** [HdrHistogram/HdrHistogram#82] opened 2015-11-04 12:11 UTC
Hi,

Depending on the recorded values, `linearBucketValues` sometimes crashes with `ArrayIndexOutOfBoundsException`.

Please find a reproducer below.

```java
private static void recordOneValueAndDisplayLinearBuckets(int value, int step) {
	IntCountsHistogram histogram = new IntCountsHistogram(2);
	histogram.recordValue(value);
	int i = 0;
	for (HistogramIterationValue itValue : histogram.linearBucketValues(step)) {
		i += step;
		System.out.println(i + ", " + itValue.getCountAddedInThisIterationStep());
	}
}

public static void main(String[] args) {
	// recordOneValueAndDisplayLinearBuckets(240, 16); would work
	recordOneValueAndDisplayLinearBuckets(241, 16);
}
```

Regards

**Comment by slandelle** [comment] 2015-11-04 12:30
The issue happens on some specific (highestRecordedValue, step), e.g.:

```
value=255 step=2
value=253 step=4
value=253 step=6
value=253 step=7
value=249 step=8
value=253 step=9
value=251 step=10
value=254 step=11
value=253 step=12
value=248 step=13
value=253 step=14
value=241 step=16
value=253 step=18
value=248 step=19
value=241 step=20
value=253 step=21
value=243 step=22
value=254 step=23
value=241 step=24
value=251 step=25
value=235 step=26
value=244 step=27
value=253 step=28
value=233 step=29
value=241 step=30
value=249 step=31
value=225 step=32
value=232 step=33
value=239 step=34
value=246 step=35
value=253 step=36
value=223 step=37
value=229 step=38
value=235 step=39
value=241 step=40
value=247 step=41
value=253 step=42
value=216 step=43
value=221 step=44
value=226 step=45
value=231 step=46
value=236 step=47
value=241 step=48
value=246 step=49
value=251 step=50
value=209 step=52
value=213 step=53
value=217 step=54
value=221 step=55
value=225 step=56
value=229 step=57
value=233 step=58
value=237 step=59
value=241 step=60
value=245 step=61
value=249 step=62
value=253 step=63
value=193 step=64
value=196 step=65
value=199 step=66
value=202 step=67
value=205 step=68
value=208 step=69
value=211 step=70
value=214 step=71
value=217 step=72
value=220 step=73
value=223 step=74
value=226 step=75
value=229 step=76
value=232 step=77
value=235 step=78
value=238 step=79
value=241 step=80
value=244 step=81
value=247 step=82
value=250 step=83
value=253 step=84
value=173 step=86
value=175 step=87
value=177 step=88
value=179 step=89
value=181 step=90
value=183 step=91
value=185 step=92
value=187 step=93
value=189 step=94
value=191 step=95
value=193 step=96
value=195 step=97
value=197 step=98
value=199 step=99
```

**Comment by giltene** [comment] 2015-11-05 18:04
The root cause of this problem is an off-by-one issue at the beginning of the iteration, where the first iteration actually includes both the 0'th linear iteration bucket and the 1st linear iteration bucket, rather than staying to the first one. This (including one too many steps at the start) then carries forward to the last bucket. I've modified the logic for both linear and logarithmic iterators now to logically deal with the lowest and highest values in the current step, rather than with the next step, such that the range traversed by the very first iteration step is of the same size as the ones that follow. See https://github.com/HdrHistogram/HdrHistogram/commit/bc7aef6c231e1215d5be1b38074203694b71ebaf

I've verified no OOB behavior with a few of the edge cases you list above. Would be great if you can review the new behavior and verify on your end. I'll leave the issue open for a bit pending verification.

**Comment by slandelle** [comment] 2015-11-05 18:10
I'll test later tonight and report.
Thanks a lot!

**Comment by slandelle** [comment] 2015-11-05 20:23
@giltene Sadly, it still seems broken.

Please find below a test that scans for broken values.

```java
private static void recordOneValueAndDisplayLinearBuckets(int value, long step) {
	IntCountsHistogram histogram = new IntCountsHistogram(2);
	histogram.recordValue(value);
	for (HistogramIterationValue itValue : histogram.linearBucketValues(step)) {
		itValue.getCountAddedInThisIterationStep();
	}
}

public static void main(String[] args) {

	List<int[]> broken = new ArrayList<>();
	//
	for (int step = 2; step < 100; step++) {
		for (int value = 1; value < 1000; value++) {
			try {
				recordOneValueAndDisplayLinearBuckets(value, step);
			} catch (ArrayIndexOutOfBoundsException e) {
				broken.add(new int[] { value, step });
			}
		}
	}
	for (int[] brk : broken) {
		System.out.println("broken: value=" + brk[0] + " step=" + brk[1]);
	}
}
```

**Comment by giltene** [comment] 2015-11-06 05:55
Ok. That edge is certainly also a problem (and probably the original one you noticed). It happens when a step covers the max value cell, but also extends past the end of the counts array. Fixed with
https://github.com/HdrHistogram/HdrHistogram/commit/016ab97811fcef1594eab6a02dd44d516624ee73 , which indicates the iteration level has been reached when the currentIndex reaches the end of the counts array. This is [very] subtly different than (nextValueAtIndex > histogram.maxValue)...
Added a test with your scan above, asserting that no AIOOB is triggered in the scan.

**Comment by mikeb01** [comment] 2015-11-06 06:41
I'll have a dig through the C implementation and see if it suffers the same problem.  Although the C iterators have very different implementation.

**Comment by slandelle** [comment] 2015-11-06 06:44
@giltene Thanks!

**Closed** 2015-11-08 18:23 UTC
